### ISSUE TITLE
How can I deploy smart contract to tron chain using foundry?

### ISSUE THREAD

**Issue by 0xtomoon** [tronprotocol/java-tron#6305]
When I run deploy script using foundry and tron rpc url, it shows this error.

`the method eth_getTransactionCount does not exist/is not available`

How can I deploy smart contract which is already working in other chains?

**Comment by Federico2014** [comment]
It is not supported for foundry to deploy smart contracts on TRON, you should use 
[TronBox](https://developers.tron.network/reference/what-is-tronbox), [Tron-IDE](https://developers.tron.network/docs/tron-ide), or [wallet-cli](https://tronprotocol.github.io/documentation-en/clients/wallet-cli/) instead.

**Comment by 0xtomoon** [comment]
> It is not supported for foundry to deploy smart contracts on TRON, you should use [TronBox](https://developers.tron.network/reference/what-is-tronbox), [Tron-IDE](https://developers.tron.network/docs/tron-ide), or [wallet-cli](https://tronprotocol.github.io/documentation-en/clients/wallet-cli/) instead.

Thanks.
Is there option to set compile option to `viaIR: true` in Tron-IDE?

**Comment by Federico2014** [comment]
@0xtomoon I am afraid not. You can use the [solc](https://github.com/tronprotocol/solidity/releases) compiler directly and it has the `--via-ir `  option.

**Comment by 0xtomoon** [comment]
@Federico2014  Are you from Tron tech team? Can we get additional support via TG?

**Comment by Federico2014** [comment]
> [@Federico2014](https://github.com/Federico2014) Are you from Tron tech team? Can we get additional support via TG?

No, I am the community developer. If you have any problems, I'd like to offer help here.

**Comment by 0xtomoon** [comment]
@Federico2014 
Does it work when I compile using foundry with solidity version v0.8.23? Or I should compile only using tron's solc?
Also after compile how can I deploy? I only used foundry or hardhat for deployment so I don't know how to deploy without using  them.

**Comment by Federico2014** [comment]
@0xtomoon To keeep compatibility, you should use TRON's solc compiler.  After compiling,  you can get the `abi`  and `bytecode`, then you deploy the contract use [deployContract](https://github.com/tronprotocol/wallet-cli?tab=readme-ov-file#How-to-use-smart-contract) command in the wallet-cli.

**Comment by hendev9** [comment]
@Federico2014 
https://github.com/tronprotocol/wallet-cli?tab=readme-ov-file#edit-configconf-in-srcmainresources
In tron wallet cli config, which ip address and port id should I add for full node and solidity node?

**Comment by 0xtomoon** [comment]
@Federico2014 
https://github.com/tronprotocol/wallet-cli?tab=readme-ov-file#edit-configconf-in-srcmainresources
In tron wallet cli config, which ip address and port id should I add for full node and solidity node?
(I don't want to run node in my local but want to use other service.)

**Comment by 0xtomoon** [comment]
@waynercheung Thanks. I added the config and run `./gradlew build` and now I see this compile error.

```
> Task :compileJava FAILED
/tron-wallet-cli/wallet-cli/src/main/gen/org/tron/api/WalletGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
```

My Java version is this one
```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

**Comment by 0xtomoon** [comment]
@waynercheung Thanks. I am running `./gradlew build` and now I see this compile error.

```
> Task :compileJava FAILED
/tron-wallet-cli/wallet-cli/src/main/gen/org/tron/api/WalletGrpc.java:7: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
```

My Java version is this one
```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

If possible, could you build it with above config and provide me the jar file?

**Comment by waynercheung** [comment]
@0xtomoon  I think you should use java8 with the command `./gradlew build -x` to compile.

**Comment by waynercheung** [comment]
@0xtomoon Does java8 work well for you?
And do you have any other problem?

**Comment by waynercheung** [comment]
> . I am running `./gradlew build` and now I see this compile error.

@0xtomoon I notice you've also created a similar issue in the wallet-cli repository (https://github.com/tronprotocol/wallet-cli/issues/833).
To ensure we can track and resolve your problem efficiently, could you please let us know which repository you'd prefer to continue the discussion in?

**Comment by GordonLtron** [comment]
Any update on this ? If no i suggest to close the issue.

**Comment by 0xtomoon** [comment]
@GordonLtron 
I faced another issue but it's not related to this issue.
Will close this issue. Thanks!
