### ISSUE TITLE
Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed

### ISSUE THREAD

**Issue by ksemaev** [tronprotocol/java-tron#2379]
1. What did you do?
Tried to run Odyssey-v3.6.1 or Odyssey-v3.6.0 on ubuntu/alpine with openjdk8/oracle-jdk-8

2. What did you expect to see?
Running normally

3. What did you see instead?

> 12:19:33.959 WARN  [main] [o.t.c.a.TronApplicationContext](AbstractApplicationContext.java:544) Exception encountered during context initialization - cancelling refresh attempt
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler.BlockMsgHandler.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetDelegate.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/tron/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.tron.core.db.Manager]: : Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair

Trying to replicate the behaviour on plain ubuntu instance with openjdk-8 installed (and with oracle jdk on another ubuntu instance ):
```
 wget -q https://github.com/tronprotocol/java-tron/releases/download/Odyssey-v3.6.1/FullNode.jar
java -jar FullNode.jar
```. (just a test without configfile) and getting the same


Maybe there're some prerequisities missing?

**Comment by ksemaev** [comment]
It works on `sullof/ubu18jdk8node10redis` docker image, what's inside of it? Maybe @sullof can share dockerfile?

**Comment by ksemaev** [comment]
seems to be openjdk issue, worked with oracle 8.221
